modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId = "allthewings"
version = "1.0.0-DEV"
displayName = "AllTheWings"
#updateJSONURL = "TO BE FILLED"
#displayURL="http://example.com/"
#logoFile="allthewings.png"
#credits="Thanks for this example mod goes to Java"
authors = "PugzAreCute"
description = '''
TO BE FILLED
'''
[[dependencies.allthewings]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.allthewings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
