modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All rights reserved"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "allthewings" #mandatory
version = "1.0.0-DEV" #mandatory
displayName = "AllTheWings" #mandatory
updateJSONURL = "TO BE FILLED" #optional
#displayURL="http://example.com/" #optional
#logoFile="allthewings.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "PugzAreCute" #optional
description = '''
TO BE FILLED
'''
[[dependencies.allthewings]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.allthewings]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
